/**
 * Tipos compartidos para los generadores de configuración contable
 */

export interface BusinessFeatures {
  // Servicios
  hasConsultationServices: boolean;  // Consultas y valoraciones
  hasMedicalTreatments: boolean;    // Tratamientos médicos
  hasHairSalon: boolean;             // Peluquería
  hasSpa: boolean;                   // Spa/Hidroterapia
  
  // Productos
  sellsProducts: boolean;            // Venta de productos
  
  // Estructura organizativa
  isMultiCenter: boolean;            // Si planea tener múltiples centros/clínicas
}

export interface ServiceCategory {
  code: string;
  name: {
    es: string;
    fr: string;
    en: string;
  };
  description?: {
    es: string;
    fr: string;
    en: string;
  };
  isActive: boolean;
}

export interface ProductFamily {
  code: string;
  name: {
    es: string;
    fr: string;
    en: string;
  };
  description?: {
    es: string;
    fr: string;
    en: string;
  };
  isForSale: boolean;
  isConsumable: boolean;
  isActive: boolean;
}

export interface DocumentSeriesTemplate {
  code: string;
  prefix: string;
  documentType: 'TICKET' | 'RECEIPT' | 'INVOICE' | 'SIMPLIFIED_INVOICE' | 'CREDIT_NOTE' | 'CORRECTIVE_INVOICE' | 'QUOTE' | 'VOUCHER' | 'WORK_ORDER' | 'DELIVERY_NOTE';
  description?: {
    es: string;
    fr: string;
    en: string;
  };
  isActive: boolean;
  resetYearly: boolean;
  nextNumber: number;
}

export interface PaymentMethodTemplate {
  name: {
    es: string;
    fr: string;
    en: string;
  };
  code: string;
  type: 'CASH' | 'CARD' | 'TRANSFER' | 'CHECK' | 'FINANCING' | 'GIFT_CARD' | 'OTHER';
  isActive: boolean;
  requiresTerminal?: boolean;
  requiresBankAccount?: boolean;
}

export interface ExtendedAccountingTemplate {
  name: string;
  description: string;
  country: string;
  accounts: any[];
  extensions: {
    serviceCategories: ServiceCategory[];
    productFamilies: ProductFamily[];
    documentSeries: DocumentSeriesTemplate[];
    paymentMethods: PaymentMethodTemplate[];
    businessFeatures: BusinessFeatures;
    accountingMappings?: AccountingMapping;
    generatedAt: string;
    version: string;
  };
}

export interface AccountingMapping {
  categories: Record<string, {
    accountCode: string;
    description: {
      es: string;
      fr?: string;
      en?: string;
    } | string;
    autoGenerated?: boolean;
  }>;
  paymentMethods: Record<string, {
    accountCode: string;
    description: {
      es: string;
      fr?: string;
      en?: string;
    } | string;
    autoGenerated?: boolean;
  }>;
  vatRates: Record<string, {
    rate: number;
    accountCode: string;
    description: string;
  }>;
  specialRules?: Array<{
    name: string;
    description: string;
    condition: string;
    action: string;
  }>;
}
