'use client'

// Este archivo sirve como punto central para exportar todos los iconos utilizados en la aplicación
// Se basa principalmente en Lucide React, que es la librería de iconos predeterminada

import {
  AlertCircle,
  ArrowRight,
  ArrowLeft,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Clock,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  type LucideIcon,
  Calendar,
  Menu,
  Search,
  Edit,
  MoreHorizontal,
  Copy,
  ChevronsUpDown,
  Bell,
  LogOut,
  // Añadir más iconos según sea necesario
} from "lucide-react"

// Exportamos todos los iconos desde Lucide
export {
  AlertCircle,
  ArrowRight,
  ArrowLeft,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Clock,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  type LucideIcon,
  Calendar,
  Menu,
  Search,
  Edit,
  MoreHorizontal,
  Copy,
  ChevronsUpDown,
  Bell,
  LogOut,
  // Añadir más iconos según sea necesario
}

// También podríamos definir iconos personalizados aquí si fuera necesario
// export const CustomIcon = () => { ... }

// Mapeo de iconos para acceso por nombre
export const Icons = {
  spinner: Loader2,
  logo: Image,
  close: X,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
} 