-- AlterTable
ALTER TABLE "SmartPlugDevice" ADD COLUMN     "apModeEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoOffDelay" INTEGER,
ADD COLUMN     "autoOffEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoUpdate" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "ledBrightness" INTEGER,
ADD COLUMN     "ledColorB" INTEGER,
ADD COLUMN     "ledColorG" INTEGER,
ADD COLUMN     "ledColorMode" TEXT,
ADD COLUMN     "ledColorR" INTEGER,
ADD COLUMN     "ledNightMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "powerLimit" DOUBLE PRECISION,
ADD COLUMN     "timezone" TEXT,
ADD COLUMN     "wifiBackupEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "wifiBackupSsid" TEXT;
